name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION to Calendar Versioning
        run: |
          VERSION=$(TZ=Asia/Tokyo date "+%Y.%m.%d")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v6
        with:
          commitish: ${{ github.event.pull_request.head.sha }}
          tag: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          version: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
